#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      extension_name: mysql_scanner
      duckdb_version: 'v0.10.2'
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
      build_duckdb_shell: false

  # Note: this workaround is required for building MacOS where extra toolchain config is required
  duckdb-stable-build-macos:
    name: Build extension binaries
    uses: ./.github/workflows/_extension_distribution_macos.yml
    with:
      duckdb_version: v0.10.2
      extension_name: mysql_scanner


  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: [duckdb-stable-build, duckdb-stable-build-macos]
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      duckdb_version: v0.10.2
      extension_name: mysql_scanner
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
